services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: auth_api
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/auth
    restart: unless-stopped
    depends_on:
      - db
      - redis
    command: air main.go -b 0.0.0.0

  db:
    image: postgres:alpine
    container_name: auth_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: auth_redis
    restart: always
    volumes:
      - ./data/redis:/data
    ports:
      - '6379:6379'
