swagger: '2.0'
info:
  title: Auth
  description: APIs for authentication/token provider and policy management
  version: 1.0.0
schemes:
  - https
paths:
  /v1/token:
    post:
      summary: Create Token
      description: Endpoint to get tokens.
      x-google-backend:
        address: https://auth-zojtpqpcfq-as.a.run.app/v1/token
      operationId: getTokens
      tags:
        - Auth
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Token request parameters
          required: true
          schema:
            $ref: '#/definitions/TokenRequest'
      responses:
        '200':
          description: Token granted
          schema:
            $ref: '#/definitions/SuccessResponse'
        '400':
          description: Bad request/Invalid request body
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /v1/token/refresh:
    post:
      summary: Refresh Token
      description: Endpoint to refresh access tokens.
      x-google-backend:
        address: https://auth-zojtpqpcfq-as.a.run.app/v1/token/refresh
      operationId: refreshToken
      tags:
        - Auth
      security:
        - BearerAuth: [ ]
      produces:
        - application/json
      responses:
        '200':
          description: Tokens refresh successful
          schema:
            $ref: '#/definitions/SuccessResponse'
        '400':
          description: Bad request/Invalid request body
          schema:
            $ref: '#/definitions/ErrorResponse'
        '401':
          description: Unauthorized. Invalid or expired token.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: Internal server error.
          schema:
            $ref: '#/definitions/ErrorResponse'
  /v1/token/revoke:
    post:
      summary: Revoke access token
      description: Revoke the access token using a bearer token.
      x-google-backend:
        address: https://auth-zojtpqpcfq-as.a.run.app/v1/token/revoke
      operationId: revokeAccessToken
      tags:
        - Auth
      produces:
        - application/json
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: Token revoked successfully
          schema:
            $ref: '#/definitions/SuccessResponse'
        '400':
          description: Bad request/Invalid request body
          schema:
            $ref: '#/definitions/ErrorResponse'
        '401':
          description: Unauthorized. Invalid or expired token.
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: Internal server error.
          schema:
            $ref: '#/definitions/ErrorResponse'
definitions:
  SuccessResponse:
    type: object
    properties:
      success:
        type: boolean
      data:
        type: object
      message:
        type: string
    required:
      - success
      - message
      - data
  ErrorResponse:
    type: object
    properties:
      success:
        type: boolean
      data:
        type: object
      message:
        type: string
      error:
        type: string
    required:
      - success
      - data
      - message
      - error
  TokenRequest:
    type: object
    properties:
      type:
        type: string
        description: Type of the token request.
      requester_id:
        type: string
        format: uuid
        description: ID of the requester (UUID v4).
      device_id:
        type: string
        description: ID of the device.
      profile_id:
        type: string
        description: Profile of the requester
      provider:
        type: string
        description: Token Provider
      at_duration:
        type: integer
        format: int64
        description: Expiry time for the access token in seconds.
      rt_duration:
        type: integer
        format: int64
        description: Expiry time for the refresh token in seconds
    required:
      - type
      - requester_id
      - device_id
      - profile_id
      - provider
securityDefinitions:
  BearerAuth:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    # The value below should be unique
    x-google-issuer: "toffeelive.com"
    x-google-jwks_uri: "https://storage.googleapis.com/toffe-dev-public-key/jwks.json"
    # Optional. Replace YOUR-CLIENT-ID with your client ID
    x-google-audiences: "https://localhost:3000"
